package com.supermite.smp.ui

import android.content.Context
import java.util.Locale

object Lang {
    private var currentLocale: Locale = Locale.getDefault()
    var language: String = "system"
        set(value) {
            field = value
            currentLocale = when (value) {
                "zh" -> Locale.SIMPLIFIED_CHINESE
                "en" -> Locale.ENGLISH
                else -> Locale.getDefault()
            }
        }

    fun get(key: String): String {
        return if (currentLocale.language == "zh") zh[key] ?: key else en[key] ?: key
    }

    private val zh = mapOf(
        "nav_subs" to "Subsonic服务器",
        "nav_library" to "音乐列表",
        "nav_settings" to "设置",
        "wait_update" to "请等待更新",
        "subsonic_dev" to "Subsonic 服务器（开发中）",
        "appearance" to "外观设置",
        "color_dark_bg" to "配色、深色模式和背景图片",
        "language" to "语言",
        "language_desc" to if (language == "zh") "中文" else "English",
        "account" to "用户帐号",
        "account_desc" to "查看或编辑本地账号，管理流媒体账号凭证",
        "storage" to "存储设置",
        "storage_desc" to "扫描、串流下载/缓存、配置文件和音乐格式转换",
        "download_list" to "下载列表",
        "no_download" to "无下载任务",
        "about" to "软件详情",
        "about_desc" to "版本号、作者、构建说明、软件介绍和 GitHub 仓库",
        "streaming" to "流媒体模式",
        "back_to_library" to "返回音乐列表",
        "subsonic_card" to "支持 Navidrome 等兼容 SubSonic API 的服务器",
        "add_server" to "添加服务器",
        "edit" to "编辑",
        "delete_server" to "删除服务器",
        "confirm_delete" to "确定删除「%s」？",
        "delete" to "删除",
        "cancel" to "取消",
        "close" to "关闭",
        "save" to "保存",
        "domain" to "域名",
        "port" to "端口（选填）",
        "username" to "用户名",
        "password" to "密码",
        "server_note" to "服务器备注",
        "ignore_cert" to "忽略证书问题",
        "subsonic_mgmt" to "Subsonic 服务器管理",
        "subsonic_add" to "添加 Subsonic 服务器",
        "subsonic_edit" to "编辑 Subsonic 服务器",
        "subsonic_info" to "Subsonic/Navidrome 服务器管理\n\n当前进度：服务器列表管理已完成，API 对接由后续开发接手。选中服务器将作为流媒体来源。",
        "metawrite" to "修改音频元数据",
        "metawrite_on" to "已开启，Last.fm 匹配到的元数据直接写入音频文件",
        "metawrite_off" to "关闭（Last.fm 匹配结果仅更新音乐库）",
        "debug_mode" to "调试模式",
        "debug_on" to "已开启，报错将产生日志文件",
        "debug_off" to "已关闭",
        "scan" to "扫描",
        "lastfm_meta" to "通过 Last.fm 获取音频元数据",
        "lastfm_desc" to "为音乐库中缺少元数据的曲目获取标题、歌手、专辑等信息。部分情况需要手动剔除错误元数据才能匹配到正确数据。",
        "lrclib_lyrics" to "尝试通过 LrcLib 获取歌词",
        "lrclib_desc" to "为音乐库中具备曲名、作者和专辑元数据的音乐匹配带时间轴的 LRC 歌词。",
        "playing" to "正在播放",
        "fav_playlist" to "我喜欢的音乐",
        "recent" to "最近播放",
        "ranking" to "播放排行",
        "permissions" to "权限",
        "permission_summary" to "通知与媒体访问",
        "playback" to "播放设置",
        "playback_summary" to "启动恢复、音频焦点、均衡器",
        "scan_page" to "扫描",
        "scan_media" to "自动扫描系统音乐库",
        "scan_media_desc" to "读取系统媒体库、CUE 文件、同名 LRC 歌词，并提取内嵌封面。",
        "scan_folder" to "选择文件夹扫描",
        "scan_folder_desc" to "授权一个音乐目录，递归扫描音频、CUE 和歌词文件。",
        "scan_import" to "手动导入文件",
        "scan_import_desc" to "选择一个或多个音频、CUE 或 LRC 文件，适合补充单曲。",
        "library" to "音乐库",
        "search_filter" to "搜索筛选",
        "collapse_filter" to "收起搜索筛选",
        "library_count" to "当前音乐库：%d 首；已识别歌词：%d 首。",
        "no_track_hint" to "暂无音乐，点击右上角扫描或手动导入",
        "playlist_list" to "播放列表",
        "music_list" to "音乐列表",
        "common_playlists" to "常用歌单",
        "auto_playlists" to "自动歌单",
        "play" to "播放",
        "pause" to "暂停",
        "prev_track" to "上一首",
        "next_track" to "下一首",
        "menu" to "菜单",
        "add_to_playlist" to "加入播放列表",
        "match_lyrics" to "匹配歌词",
        "match_metadata" to "匹配元数据",
        "get_cover" to "获取封面",
        "edit_info" to "编辑音乐信息",
        "edit_metadata" to "编辑音频元数据",
        "remove_from_playlist" to "从当前播放列表移除",
        "album" to "专辑",
        "artist_label" to "歌手",
        "composer_label" to "作曲",
        "year_label" to "年份",
        "cover_label" to "封面",
        "select_cover" to "选择封面图片",
        "write_metadata" to "写入",
        "edit_audio_meta" to "编辑音频元数据",
        "stream_preload" to "串流预加载",
        "streaming_page" to "流媒体",
        "streaming_mode" to "流媒体模式",
        "dizzylab_card" to "DizzyLab",
        "dizzylab_not_logged" to "未登录，点击登录或加载账户专辑",
        "dizzylab_logged" to "已登录，点击加载账户专辑",
        "webdav_card" to "WebDav 服务器",
        "return_to_stream" to "返回流媒体来源",
        "search_purchased" to "搜索已购专辑",
        "online_search" to "在线搜索",
        "load_more" to "加载更多",
        "permission_card" to "权限",
        "notification_permission" to "通知",
        "audio_permission" to "音频",
        "all_files_permission" to "所有文件访问权限",
        "playback_settings" to "播放设置",
        "restore_playback" to "启动恢复",
        "audio_focus" to "音频焦点",
        "eq_preset" to "均衡器预设",
        "play_mode" to "播放模式",
        "sequential" to "顺序播放",
        "repeat_one" to "单曲循环",
        "true_random" to "真随机",
        "pseudo_random" to "伪随机",
        "speed" to "倍速",
    )

    private val en = mapOf(
        "nav_subs" to "Subsonic",
        "nav_library" to "Library",
        "nav_settings" to "Settings",
        "wait_update" to "Please wait for update",
        "subsonic_dev" to "Subsonic (Under Development)",
        "appearance" to "Appearance",
        "color_dark_bg" to "Color, Dark Mode & Background",
        "language" to "Language",
        "language_desc" to if (language == "zh") "中文" else "English",
        "account" to "Account",
        "account_desc" to "Manage local profile and streaming credentials",
        "storage" to "Storage",
        "storage_desc" to "Scan, download/cache, config and format conversion",
        "download_list" to "Downloads",
        "no_download" to "No active downloads",
        "about" to "About",
        "about_desc" to "Version, author, build info and GitHub",
        "streaming" to "Streaming",
        "back_to_library" to "Back to Library",
        "subsonic_card" to "Supports Navidrome and other SubSonic-compatible servers",
        "add_server" to "Add Server",
        "edit" to "Edit",
        "delete_server" to "Delete Server",
        "confirm_delete" to "Delete '%s'?",
        "delete" to "Delete",
        "cancel" to "Cancel",
        "close" to "Close",
        "save" to "Save",
        "domain" to "Domain",
        "port" to "Port (optional)",
        "username" to "Username",
        "password" to "Password",
        "server_note" to "Note",
        "ignore_cert" to "Ignore certificate issues",
        "subsonic_mgmt" to "Subsonic Server Management",
        "subsonic_add" to "Add Subsonic Server",
        "subsonic_edit" to "Edit Subsonic Server",
        "subsonic_info" to "Subsonic/Navidrome Server Management\n\nCurrent progress: Server list management is complete. API integration will be handled by the next developer. Selected server will be used as streaming source.",
        "metawrite" to "Auto-Write Metadata",
        "metawrite_on" to "On - Last.fm matched metadata written to audio files",
        "metawrite_off" to "Off - Last.fm results only update library",
        "debug_mode" to "Debug Mode",
        "debug_on" to "On - errors logged to file",
        "debug_off" to "Off",
        "scan" to "Scan",
        "lastfm_meta" to "Fetch Metadata via Last.fm",
        "lastfm_desc" to "Retrieve title, artist, album, etc. for tracks missing metadata. Manual cleanup of incorrect metadata may be needed for accurate results.",
        "lrclib_lyrics" to "Fetch Lyrics via LrcLib",
        "lrclib_desc" to "Match timed LRC lyrics for tracks with complete title, artist and album metadata.",
        "playing" to "Now Playing",
        "fav_playlist" to "Favorites",
        "recent" to "Recently Played",
        "ranking" to "Most Played",
        "permissions" to "Permissions",
        "permission_summary" to "Notification & media access",
        "playback" to "Playback",
        "playback_summary" to "Resume on launch, audio focus, equalizer",
        "scan_page" to "Scan",
        "scan_media" to "Auto-scan system library",
        "scan_media_desc" to "Read MediaStore, CUE files, LRC lyrics and embedded covers",
        "scan_folder" to "Select folder to scan",
        "scan_folder_desc" to "Authorize a music directory, recursive scan audio, CUE and lyric files",
        "scan_import" to "Import files manually",
        "scan_import_desc" to "Select one or more audio, CUE or LRC files",
        "library" to "Library",
        "search_filter" to "Search/Filter",
        "collapse_filter" to "Collapse Filter",
        "library_count" to "Total: %d tracks, lyrics: %d",
        "no_track_hint" to "No music - tap top-right to scan or import",
        "playlist_list" to "Playlists",
        "music_list" to "Music",
        "common_playlists" to "Common",
        "auto_playlists" to "Auto",
        "play" to "Play",
        "pause" to "Pause",
        "prev_track" to "Previous",
        "next_track" to "Next",
        "menu" to "Menu",
        "add_to_playlist" to "Add to Playlist",
        "match_lyrics" to "Match Lyrics",
        "match_metadata" to "Match Metadata",
        "get_cover" to "Get Cover",
        "edit_info" to "Edit Info",
        "edit_metadata" to "Edit Audio Metadata",
        "remove_from_playlist" to "Remove from Playlist",
        "album" to "Album",
        "artist_label" to "Artist",
        "composer_label" to "Composer",
        "year_label" to "Year",
        "cover_label" to "Cover",
        "select_cover" to "Select Cover Image",
        "write_metadata" to "Write",
        "edit_audio_meta" to "Edit Audio Metadata",
        "stream_preload" to "Stream Preload",
        "streaming_page" to "Streaming",
        "streaming_mode" to "Streaming Mode",
        "dizzylab_card" to "DizzyLab",
        "dizzylab_not_logged" to "Not logged in, tap to login or load albums",
        "dizzylab_logged" to "Logged in, tap to load albums",
        "webdav_card" to "WebDav Server",
        "return_to_stream" to "Back to Streaming Sources",
        "search_purchased" to "Search purchased albums",
        "online_search" to "Search Online",
        "load_more" to "Load More",
        "permission_card" to "Permissions",
        "notification_permission" to "Notification",
        "audio_permission" to "Audio",
        "all_files_permission" to "All Files Access",
        "playback_settings" to "Playback Settings",
        "restore_playback" to "Resume on Launch",
        "audio_focus" to "Audio Focus",
        "eq_preset" to "Equalizer Preset",
        "play_mode" to "Play Mode",
        "sequential" to "Sequential",
        "repeat_one" to "Repeat One",
        "true_random" to "True Random",
        "pseudo_random" to "Pseudo Random",
        "speed" to "Speed",
    )
}
